// Bundles the MCP Apps widget into one self-contained HTML string. Hosts load it in a
// sandboxed iframe with no network, and the Worker has no filesystem, so the page is
// inlined into a generated module that every server entry point imports.
import { readFile, writeFile } from "node:fs/promises";
import { build } from "esbuild";

const widgetDir = new URL("../src/mcp/widget/", import.meta.url);
const outFile = new URL("../src/mcp/widget-html.generated.ts", import.meta.url);

export async function renderWidgetModule() {
  const [script, css] = await Promise.all([
    build({
      bundle: true,
      entryPoints: [new URL("app.ts", widgetDir).pathname],
      format: "iife",
      legalComments: "none",
      minify: true,
      target: "es2022",
      write: false,
    }),
    readFile(new URL("styles.css", widgetDir), "utf8"),
  ]);
  // esbuild escapes "</script" inside strings when bundling for the browser.
  const js = script.outputFiles[0].text;
  const html = [
    "<!doctype html>",
    '<html lang="en">',
    '<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">',
    `<style>${css}</style></head>`,
    '<body><main id="root" class="widget" hidden></main>',
    `<script>${js}</script>`,
    "</body></html>",
  ].join("\n");
  return [
    "// Generated by scripts/build-widget.mjs from src/mcp/widget. Do not edit.",
    `export const WIDGET_HTML = ${JSON.stringify(html)};`,
    "",
  ].join("\n");
}

if (process.argv[1] === new URL(import.meta.url).pathname) {
  await writeFile(outFile, await renderWidgetModule());
}
